SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `booking` (
    `Username` varchar(30) NOT NULL,
    `StartDate` DATE NOt NULL,
    `EndDate`DATE NOT NULL,
    `VehicleType` varchar(5) NOT NULL,
    `VehicleID` int(10)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `car` (
    `VehicleID` int(10) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`VehicleId`),
    `Vehiclename` varchar(20) NOT NULL,	
    `manufacturer` varchar(20) NOT NULL,
    `variant` char(1) NOT NULL,
    `class` varchar(10) NOT NULL,	
    `transmission`	varchar(10) NOT NULL,
    `price`	int (5) NOT NULL,
    `type` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `car` (`Vehiclename` , `manufacturer` , `variant` ,	`class` , `transmission` , `price` , `type`) VALUES
('Creta','Hyundai','P','SUV','M',1500,'Economical'),
('Creta','Hyundai','P','SUV','A',1700,'Economical'),
('Creta','Hyundai','D','SUV','M',1625,'Economical'),
('Creta','Hyundai','D','SUV','A',1800,'Economical'),
('Swift','Maruti Suzuki','P','Hatchback','M',850,'Economical'),
('Swift','Maruti Suzuki','P','Hatchback','A',1050,'Economical'),
('Swift','Maruti Suzuki','D','Hatchback','M',950,'Economical'),
('Swift','Maruti Suzuki','D','Hatchback','A',1150,'Economical'),
('Honda City','Honda','P','Sedan','M',1200,'Economical'),
('Honda City','Honda','P','Sedan','A',1380,'Economical'),
('Honda City','Honda','D','Sedan','M',1300,'Economical'),
('Honda City','Honda','D','Sedan','A',1450,'Economical'),
('Wagon R','Maruti Suzuki','P','Hatchback','M',800,'Economical'),
('Wagon R','Maruti Suzuki','P','Hatchback','A',900,'Economical'),
('Innova Crysta','Toyota','D','SUV','M',2200,'Economical'),
('Innova Crysta','Toyota','D','SUV','A',2400,'Economical'),
('Rapid','Skoda','P','Sedan','M',1400,'Economical'),
('Rapid','Skoda','D','Sedan','M',1500,'Economical'),
('Swift Dzire','Maruti Suzuki','P','Sedan','M', 1000 ,'Economical'),
('Swift Dzire','Maruti Suzuki','P','Sedan','A', 1150 ,'Economical'),
('i10', 'Hyundai','P','Hatchback','M',680,'Economical'),
('i20','Hyundai','P','Hatchback','M',720,'Economical'),
('Brezza','Maruti Suzuki','P','SUV','M',1100,'Economical'),
('Brezza','Maruti Suzuki','P','SUV','A',1200,'Economical'),
('Duster','Renault','P','SUV','M',1200,'Economical'),
('Baleno','Maruti Suzuki','P','Hatchback','M',895,'Economical'),
('Baleno','Maruti Suzuki','D','Hatchback','M',960,'Economical'),
('Baleno','Maruti Suzuki','P','Hatchback','A',1050,'Economical'),
('XUV','Mahindra','P','SUV','M',2100,'Economical'),
('XUV','Mahindra','D','SUV','M',2300,'Economical'),
('XUV','Mahindra','D','SUV','A',2400,'Economical'),
('Alto K10','Maruti Suzuki','P','Hatchback','M',600,'Economical'),
('Alto K10','Maruti Suzuki','P','Hatchback','A',689,'Economical'),
('Octavia','Skoda','D','Sedan','M',1800,'Economical'),
('Superb','Skoda','P','Sedan','M',2100,'Economical'),
('Superb','Skoda','D','Sedan','A',2350,'Economical'),
('Ciaz','Maruti Suzuki','P','Sedan','M',1300,'Economical'),
('Ciaz ','Maruti Suzuki','P','Sedan','A',1450,'Economical'),
('Kwid','Renault','P','Hatchback','M',615,'Economical'),
('Kwid','Renault','P','Hatchback','A',750,'Economical'),
('Elantra','Hyundai','P','Sedan','M',2350,'Economical'),
('Tuscon','Hyundai','D','SUV','M',2700,'Economical'),
('Verna','Hyundai','P','Sedan','M',1500,'Economical'),
('Verna ','Hyundai','D','Sedan','M',1600,'Economical'),
('Verna ','Hyundai','P','Sedan','A',1700,'Economical'),
('Verna ','Hyundai','D','Sedan','A',1800,'Economical'),
('Nexon','Tata','P','SUV','M',2200,'Economical'),
('Nexon','Tata','D','SUV','M',2350,'Economical'),
('Tiago','Tata','P','Hatchback','M',700,'Economical'),
('Harrier','Tata','D','SUV','M',1950,'Economical'),
('Harrier','Tata','D','SUV','A',2050,'Economical'),
('A4','Audi','P','Sedan','A',4200,'Premium'),
('A4','Audi','D','Sedan','A',4350,'Premium'),
('A6','Audi','P','Sedan','A',5300,'Premium'),
('Q7','Audi','P','SUV','A',5500,'Premium'),
('Q7','Audi','D','SUV','A',6100,'Premium'),
('Q5','Audi','P','SUV','A',5800,'Premium'),
('Q5','Audi','D','SUV','A',5950,'Premium'),
('XE','Jaguar','D','Sedan','A',4800,'Premium'),
('XF','Jaguar','D','Sedan','A',5000,'Premium');

CREATE TABLE IF NOT EXISTS `bike` (
    `VehicleID` int(10) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`VehicleID`),
    `Vehiclename` varchar(20) NOT NULL,
    `manufacturer`	varchar(20) NOT NULL,
    `displacement`	int (4) NOT NULL,
    `style`	varchar(20) NOT NULL,
    `price`int (10) NOT NULL,
   	`type` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `bike` (`Vehiclename` , `manufacturer` , `displacement` , `style` , `price`, `type`) VALUES
('Activa','Honda',110,'Scooter',110,'Economical'),
('Dio','Honda',110,'Scooter',110,'Economical'),
('Access','Suzuki',125,'Scooter',125,'Economical'),
('Jupiter','TVS',110,'Scooter',110,'Economical'),
('Activa 125','Honda',125,'Scooter',125,'Economical'),
('Ray','Yamaha',125,'Scooter',125,'Economical'),
('Lets','Suzuki',110,'Scooter',110,'Economical'),
('Maestro','Hero',110,'Scooter',110,'Economical'),
('SR 150','Aprilia',150,'Scooter',150,'Economical'),
('Pulsar 150','Bajaj',150,'Street',150,'Economical'),
('Pulsar NS200','Bajaj',200,'Street',200,'Economical'),
('FZ S','Yamaha',153,'Street',153,'Economical'),
('Duke 200','KTM',200,'Street',200,'Economical'),
('Apache','TVS',160,'Street',160,'Economical'),
('Splendor','Hero',100,'Street',100,'Economical'),
('Duke 250','KTM',250,'Street',250,'Economical'),
('Gixxer','Suzuki',155,'Street',155,'Economical'),
('Glamour','Hero',120,'Street',120,'Economical'),
('Passion PRO','Hero',100,'Street',100,'Economical'),
('Classic 350','Royal Enfield',350,'Cruiser',350,'Economical'),
('Bullet 350','Royal Enfield',350,'Cruiser',350,'Economical'),
('Thunderbird','Royal Enfield',350,'Cruiser',350,'Economical'),
('Dominar 250','Bajaj',250,'Cruiser',250,'Economical'),
('Perak','Jawa',334,'Cruiser',334,'Economical'),
('42','Jawa',293,'Cruiser',293,'Economical'),
('Dominar 400','Bajaj',400,'Cruiser',400,'Economical'),
('Imperiale','Benelli',400,'Cruiser',400,'Economical'),
('Avenger','Bajaj',160,'Cruiser',160,'Economical'),
('Street 750','Harley-Davidson',750,'Cruiser',750,'Premium'),
('Iron 883','Harley-Davidson',883,'Cruiser',883,'Premium'),
('Vulcan S','Kawasaki',650,'Cruiser',650,'Premium'),
('Rocket 3','Triumph',2500,'Cruiser',2500,'Premium'),
('Forty Eight','Harley-Davidson',1200,'Cruiser',1200,'Premium'),
('Fat Boy','Harley-Davidson',1800,'Cruiser',1800,'Premium'),
('CVO Limited','Harley-Davidson',1800,'Cruiser',1800,'Premium'),
('R15','Yamaha',155,'Sport',155,'Economical'),
('Apache RR310','TVS',310,'Sport',310,'Economical'),
('Ninja','Kawasaki',300,'Sport',300,'Economical'),
('RC 390','KTM',390,'Sport',390,'Economical'),
('Hayabusa','Suzuki',1340,'Sport',1340,'Premium'),
('Ninja ZX','Kawasaki',1000,'Sport',1000,'Premium'),
('S1000','BMW',1000,'Sport',1000,'Premium'),
('R1','Yamaha',1000,'Sport',1000,'Premium'),
('Panigale 959','Ducati',959,'Sport',959,'Premium'),
('CBR','Honda',1000,'Sport',1000,'Premium'),
('302R','Benelli',300,'Sport',300,'Economical'),
('Panigale V4 R','Ducati',1000,'Sport',1000,'Premium'),
('GT650R','Hyosung',650,'Sport',650,'Premium'),
('RSV4 RF','Aprilia',1000,'Sport',1000,'Premium'),
('Ninja H2R','Kawasaki',1000,'Sport',1000,'Premium');
